-- Run on an existing database before deploying the daily missed-day UI.
-- The app backfills each finished Seoul day inside the current plan period
-- from task creation dates and execution records. A row remains after a later
-- execution of the task.
begin;

create table if not exists public.task_missed_days (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  workspace_id text not null,
  task_id bigint not null references public.tasks(id) on delete cascade,
  missed_day date not null,
  task_title text not null,
  due_date date not null,
  created_at timestamptz not null default now()
);

create unique index if not exists task_missed_days_owner_task_day_uidx
  on public.task_missed_days (user_id, task_id, missed_day);
create index if not exists task_missed_days_owner_day_idx
  on public.task_missed_days (user_id, workspace_id, missed_day desc);

alter table public.task_missed_days enable row level security;

drop policy if exists "owner task missed days read" on public.task_missed_days;
drop policy if exists "owner task missed days insert" on public.task_missed_days;
create policy "owner task missed days read"
  on public.task_missed_days for select to authenticated
  using (
    (select private.is_auth_session_active())
    and auth.uid() is not null
    and user_id = auth.uid()
  );
create policy "owner task missed days insert"
  on public.task_missed_days for insert to authenticated
  with check (
    (select private.is_auth_session_active())
    and auth.uid() is not null
    and user_id = auth.uid()
    and exists (
      select 1 from public.tasks
      where tasks.id = task_missed_days.task_id
        and tasks.user_id = auth.uid()
        and tasks.workspace_id = task_missed_days.workspace_id
    )
  );

revoke all on table public.task_missed_days from anon, authenticated;
grant select, insert on table public.task_missed_days to authenticated;
grant usage, select on sequence public.task_missed_days_id_seq to authenticated;

notify pgrst, 'reload schema';

commit;
