-- PDS Diary: 로그인 없이 한 개의 공개 워크스페이스를 사용하는 초기 스키마입니다.
-- 배포 전 실제 운영 목적에 맞게 workspace_id 정책과 쓰기 권한을 검토하세요.

create table if not exists public.plan_versions (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  version integer not null,
  title text not null,
  start_date date not null,
  end_date date not null,
  priority text not null check (priority in ('high', 'medium', 'low')),
  success_criteria text not null,
  expected_days integer not null check (expected_days > 0),
  created_at timestamptz not null default now(),
  unique (workspace_id, version)
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  plan_version integer not null,
  activity_date date not null,
  minutes integer not null check (minutes > 0),
  note text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.reflections (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  plan_version integer not null,
  reflection_date date not null,
  mood text not null check (mood in ('great', 'good', 'okay', 'hard')),
  went_well text not null,
  next_action text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  plan_version integer not null,
  seed_key text,
  title text not null,
  due_date date not null,
  priority text not null check (priority in ('high', 'medium', 'low')),
  tags text[] not null default '{}',
  estimated_minutes integer not null check (estimated_minutes > 0),
  is_completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, seed_key)
);

create table if not exists public.task_execution_logs (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  task_id bigint not null references public.tasks(id) on delete cascade,
  start_time timestamptz not null,
  end_time timestamptz not null,
  actual_minutes integer not null check (actual_minutes > 0),
  blocker_reason text not null default '',
  created_at timestamptz not null default now(),
  check (end_time > start_time)
);

create table if not exists public.task_completion_events (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  task_id bigint not null references public.tasks(id) on delete cascade,
  completed_at timestamptz not null default now(),
  unique (workspace_id, task_id)
);

create index if not exists plan_versions_workspace_version_idx
  on public.plan_versions (workspace_id, version desc);
create index if not exists activity_logs_workspace_date_idx
  on public.activity_logs (workspace_id, activity_date desc);
create index if not exists reflections_workspace_date_idx
  on public.reflections (workspace_id, reflection_date desc);
create index if not exists tasks_workspace_status_due_idx
  on public.tasks (workspace_id, is_completed, due_date);
create index if not exists tasks_workspace_priority_idx
  on public.tasks (workspace_id, priority);
create index if not exists task_execution_logs_task_start_idx
  on public.task_execution_logs (task_id, start_time desc);
create index if not exists task_completion_events_workspace_completed_idx
  on public.task_completion_events (workspace_id, completed_at desc);

alter table public.plan_versions enable row level security;
alter table public.activity_logs enable row level security;
alter table public.reflections enable row level security;
alter table public.tasks enable row level security;
alter table public.task_execution_logs enable row level security;
alter table public.task_completion_events enable row level security;

drop policy if exists "public plan versions read" on public.plan_versions;
drop policy if exists "public plan versions insert" on public.plan_versions;
drop policy if exists "public activities read" on public.activity_logs;
drop policy if exists "public activities insert" on public.activity_logs;
drop policy if exists "public reflections read" on public.reflections;
drop policy if exists "public reflections insert" on public.reflections;
drop policy if exists "public tasks read" on public.tasks;
drop policy if exists "public tasks insert" on public.tasks;
drop policy if exists "public tasks update" on public.tasks;
drop policy if exists "public tasks delete" on public.tasks;
drop policy if exists "public task execution logs read" on public.task_execution_logs;
drop policy if exists "public task execution logs insert" on public.task_execution_logs;
drop policy if exists "public task completion events read" on public.task_completion_events;

create policy "public plan versions read" on public.plan_versions for select to anon
  using (workspace_id = 'ccna-main');
create policy "public plan versions insert" on public.plan_versions for insert to anon
  with check (workspace_id = 'ccna-main');
create policy "public activities read" on public.activity_logs for select to anon
  using (workspace_id = 'ccna-main');
create policy "public activities insert" on public.activity_logs for insert to anon
  with check (workspace_id = 'ccna-main');
create policy "public reflections read" on public.reflections for select to anon
  using (workspace_id = 'ccna-main');
create policy "public reflections insert" on public.reflections for insert to anon
  with check (workspace_id = 'ccna-main');

create policy "public tasks read" on public.tasks for select to anon
  using (workspace_id = 'ccna-main');
create policy "public tasks insert" on public.tasks for insert to anon
  with check (workspace_id = 'ccna-main');
create policy "public tasks update" on public.tasks for update to anon
  using (workspace_id = 'ccna-main')
  with check (workspace_id = 'ccna-main');
create policy "public tasks delete" on public.tasks for delete to anon
  using (workspace_id = 'ccna-main');

create policy "public task execution logs read" on public.task_execution_logs for select to anon
  using (workspace_id = 'ccna-main');
create policy "public task execution logs insert" on public.task_execution_logs for insert to anon
  with check (workspace_id = 'ccna-main');
create policy "public task completion events read" on public.task_completion_events for select to anon
  using (workspace_id = 'ccna-main');

create or replace function public.record_task_completion_once()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.is_completed = true and old.is_completed = false then
    insert into public.task_completion_events (workspace_id, task_id, completed_at)
    values (new.workspace_id, new.id, coalesce(new.completed_at, now()))
    on conflict (workspace_id, task_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists tasks_record_completion_once on public.tasks;
create trigger tasks_record_completion_once
after update of is_completed on public.tasks
for each row execute function public.record_task_completion_once();

insert into public.task_completion_events (workspace_id, task_id, completed_at)
select workspace_id, id, coalesce(completed_at, updated_at, now())
from public.tasks
where is_completed = true
on conflict (workspace_id, task_id) do nothing;

-- 계획 버전과 실행 기록은 추가 전용이며, 할 일만 상태 변경과 수정/삭제를 허용합니다.
