-- PDS Diary authenticated schema.
-- Authentication: Supabase Auth email/password
-- Authorization: every row belongs to auth.uid() and is protected by RLS.
-- Existing public pds-main rows remain nullable until card1-migrate-existing-data.sql is run.

drop table if exists public.activity_logs;

create table if not exists public.plan_versions (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() references auth.users(id) on delete cascade,
  workspace_id text not null,
  version integer not null,
  title text not null,
  start_date date not null,
  end_date date not null,
  priority text not null check (priority in ('high', 'medium', 'low')),
  success_criteria text not null,
  expected_days integer not null check (expected_days > 0),
  carryover_note text not null default '',
  created_at timestamptz not null default now()
);

alter table public.plan_versions
  add column if not exists carryover_note text not null default '';
alter table public.plan_versions
  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.plan_versions
  alter column user_id set default auth.uid();

create table if not exists public.reflections (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() references auth.users(id) on delete cascade,
  workspace_id text not null,
  plan_version integer not null,
  reflection_date date not null,
  mood text not null check (mood in ('great', 'good', 'okay', 'hard')),
  went_well text not null,
  next_action text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.reflections
  add column if not exists updated_at timestamptz;
alter table public.reflections
  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.reflections
  alter column user_id set default auth.uid();

update public.reflections
set updated_at = created_at
where updated_at is null;

alter table public.reflections
  alter column updated_at set default now(),
  alter column updated_at set not null;

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() references auth.users(id) on delete cascade,
  workspace_id text not null,
  plan_version integer not null,
  seed_key text,
  title text not null,
  due_date date not null,
  priority text not null check (priority in ('high', 'medium', 'low')),
  tags text[] not null default '{}',
  estimated_minutes integer not null check (estimated_minutes > 0),
  is_completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tasks
  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.tasks
  alter column user_id set default auth.uid();

create table if not exists public.task_execution_logs (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() references auth.users(id) on delete cascade,
  workspace_id text not null,
  task_id bigint not null references public.tasks(id) on delete cascade,
  start_time timestamptz not null,
  end_time timestamptz not null,
  actual_minutes integer not null check (actual_minutes > 0),
  blocker_reason text not null default '',
  created_at timestamptz not null default now(),
  check (end_time > start_time)
);

alter table public.task_execution_logs
  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.task_execution_logs
  alter column user_id set default auth.uid();

create table if not exists public.task_completion_events (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() references auth.users(id) on delete cascade,
  workspace_id text not null,
  task_id bigint not null references public.tasks(id) on delete cascade,
  completed_at timestamptz not null default now(),
  completed_day date not null
);

alter table public.task_completion_events
  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.task_completion_events
  alter column user_id set default auth.uid();
alter table public.task_completion_events
  add column if not exists completed_day date;
update public.task_completion_events
set completed_day = (completed_at at time zone 'Asia/Seoul')::date
where completed_day is null;
alter table public.task_completion_events
  alter column completed_day set not null;

-- Replace the former single-workspace uniqueness rules with per-user rules.
alter table public.plan_versions
  drop constraint if exists plan_versions_workspace_id_version_key;
alter table public.tasks
  drop constraint if exists tasks_workspace_id_seed_key_key;
alter table public.task_completion_events
  drop constraint if exists task_completion_events_workspace_id_task_id_key;

create unique index if not exists plan_versions_owner_workspace_version_uidx
  on public.plan_versions (user_id, workspace_id, version);
create unique index if not exists tasks_owner_workspace_seed_uidx
  on public.tasks (user_id, workspace_id, seed_key);
drop index if exists public.task_completion_events_owner_task_uidx;
create unique index if not exists task_completion_events_owner_task_day_uidx
  on public.task_completion_events (user_id, task_id, completed_day);

create index if not exists plan_versions_owner_workspace_version_idx
  on public.plan_versions (user_id, workspace_id, version desc);
create index if not exists reflections_owner_workspace_date_idx
  on public.reflections (user_id, workspace_id, reflection_date desc);
create index if not exists tasks_owner_workspace_status_due_idx
  on public.tasks (user_id, workspace_id, is_completed, due_date);
create index if not exists tasks_owner_workspace_priority_idx
  on public.tasks (user_id, workspace_id, priority);
create index if not exists task_execution_logs_owner_start_idx
  on public.task_execution_logs (user_id, start_time desc);
create index if not exists task_completion_events_owner_completed_idx
  on public.task_completion_events (user_id, completed_at desc);

alter table public.plan_versions enable row level security;
alter table public.reflections enable row level security;
alter table public.tasks enable row level security;
alter table public.task_execution_logs enable row level security;
alter table public.task_completion_events enable row level security;

-- A valid JWT alone is not enough for diary access. Supabase access tokens can
-- remain cryptographically valid until exp after logout, so every request also
-- has to prove that its session_id still exists in Auth's server-side session
-- table. Keep this helper outside the exposed public schema.
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create or replace function private.is_auth_session_active()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from auth.sessions
    where auth.sessions.id::text = nullif(auth.jwt() ->> 'session_id', '')
      and auth.sessions.user_id = auth.uid()
  );
$$;

revoke all on function private.is_auth_session_active() from public;
grant execute on function private.is_auth_session_active() to authenticated;

create or replace function private.check_auth_session()
returns void
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if auth.role() = 'authenticated' and not private.is_auth_session_active() then
    raise insufficient_privilege using
      message = 'The authentication session is no longer active.';
  end if;
end;
$$;

revoke all on function private.check_auth_session() from public;
grant execute on function private.check_auth_session() to authenticated;

-- PostgREST runs this before each Data API request. A revoked session therefore
-- receives an HTTP error instead of an RLS-filtered 200 with an empty array.
alter role authenticator set pgrst.db_pre_request = 'private.check_auth_session';
notify pgrst, 'reload config';

-- Remove every policy used by the public T06 workspace and prior runs of this file.
drop policy if exists "public plan versions read" on public.plan_versions;
drop policy if exists "public plan versions insert" on public.plan_versions;
drop policy if exists "public reflections read" on public.reflections;
drop policy if exists "public reflections insert" on public.reflections;
drop policy if exists "public reflections update" on public.reflections;
drop policy if exists "public reflections delete" on public.reflections;
drop policy if exists "public tasks read" on public.tasks;
drop policy if exists "public tasks insert" on public.tasks;
drop policy if exists "public tasks update" on public.tasks;
drop policy if exists "public tasks delete" on public.tasks;
drop policy if exists "public task execution logs read" on public.task_execution_logs;
drop policy if exists "public task execution logs insert" on public.task_execution_logs;
drop policy if exists "public task execution logs update" on public.task_execution_logs;
drop policy if exists "public task execution logs delete" on public.task_execution_logs;
drop policy if exists "public task completion events read" on public.task_completion_events;
drop policy if exists "owner plan versions read" on public.plan_versions;
drop policy if exists "owner plan versions insert" on public.plan_versions;
drop policy if exists "owner reflections all" on public.reflections;
drop policy if exists "owner tasks all" on public.tasks;
drop policy if exists "owner task execution logs all" on public.task_execution_logs;
drop policy if exists "owner task completion events read" on public.task_completion_events;

create policy "owner plan versions read"
  on public.plan_versions for select to authenticated
  using (
    (select private.is_auth_session_active())
    and auth.uid() is not null
    and user_id = auth.uid()
  );
create policy "owner plan versions insert"
  on public.plan_versions for insert to authenticated
  with check (
    (select private.is_auth_session_active())
    and auth.uid() is not null
    and user_id = auth.uid()
  );

create policy "owner reflections all"
  on public.reflections for all to authenticated
  using (
    (select private.is_auth_session_active())
    and auth.uid() is not null
    and user_id = auth.uid()
  )
  with check (
    (select private.is_auth_session_active())
    and auth.uid() is not null
    and user_id = auth.uid()
  );

create policy "owner tasks all"
  on public.tasks for all to authenticated
  using (
    (select private.is_auth_session_active())
    and auth.uid() is not null
    and user_id = auth.uid()
  )
  with check (
    (select private.is_auth_session_active())
    and auth.uid() is not null
    and user_id = auth.uid()
  );

create policy "owner task execution logs all"
  on public.task_execution_logs for all to authenticated
  using (
    (select private.is_auth_session_active())
    and auth.uid() is not null
    and user_id = auth.uid()
  )
  with check (
    (select private.is_auth_session_active())
    and auth.uid() is not null
    and user_id = auth.uid()
    and exists (
      select 1
      from public.tasks
      where tasks.id = task_execution_logs.task_id
        and tasks.user_id = auth.uid()
    )
  );

create policy "owner task completion events read"
  on public.task_completion_events for select to authenticated
  using (
    (select private.is_auth_session_active())
    and auth.uid() is not null
    and user_id = auth.uid()
  );

-- The browser can no longer use the public anonymous role for diary data.
revoke all on table public.plan_versions from anon, authenticated;
revoke all on table public.reflections from anon, authenticated;
revoke all on table public.tasks from anon, authenticated;
revoke all on table public.task_execution_logs from anon, authenticated;
revoke all on table public.task_completion_events from anon, authenticated;

grant select, insert on table public.plan_versions to authenticated;
grant select, insert, update, delete on table public.reflections to authenticated;
grant select, insert, update, delete on table public.tasks to authenticated;
grant select, insert, update, delete on table public.task_execution_logs to authenticated;
grant select on table public.task_completion_events to authenticated;

grant usage, select on sequence public.plan_versions_id_seq to authenticated;
grant usage, select on sequence public.reflections_id_seq to authenticated;
grant usage, select on sequence public.tasks_id_seq to authenticated;
grant usage, select on sequence public.task_execution_logs_id_seq to authenticated;
grant usage, select on sequence public.task_completion_events_id_seq to authenticated;

create or replace function public.record_task_completion_for_day()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  completion_time timestamptz;
  completion_day date;
begin
  completion_time := coalesce(new.completed_at, now());
  completion_day := (completion_time at time zone 'Asia/Seoul')::date;
  if new.is_completed = true and (
    old.is_completed = false or
    (old.completed_at at time zone 'Asia/Seoul')::date is distinct from completion_day
  ) then
    insert into public.task_completion_events (user_id, workspace_id, task_id, completed_at, completed_day)
    values (new.user_id, new.workspace_id, new.id, completion_time, completion_day)
    on conflict (user_id, task_id, completed_day)
    do update set completed_at = excluded.completed_at;
  elsif old.is_completed = true and new.is_completed = false then
    -- An unchecked task must disappear from today's record. After midnight,
    -- the previous day's event is retained as the final daily state.
    delete from public.task_completion_events
    where user_id = old.user_id and task_id = old.id
      and completed_day = (now() at time zone 'Asia/Seoul')::date;
  end if;
  return new;
end;
$$;

revoke all on function public.record_task_completion_for_day() from public;

drop trigger if exists tasks_record_completion_once on public.tasks;
drop trigger if exists tasks_record_completion_for_day on public.tasks;
drop function if exists public.record_task_completion_once();
create trigger tasks_record_completion_for_day
after update of is_completed, completed_at on public.tasks
for each row execute function public.record_task_completion_for_day();

insert into public.task_completion_events (user_id, workspace_id, task_id, completed_at, completed_day)
select user_id, workspace_id, id, coalesce(completed_at, updated_at, now()),
  (coalesce(completed_at, updated_at, now()) at time zone 'Asia/Seoul')::date
from public.tasks
where is_completed = true
  and user_id is not null
on conflict (user_id, task_id, completed_day) do nothing;

delete from public.task_completion_events e
using public.tasks t
where e.task_id = t.id and e.user_id = t.user_id
  and e.completed_day = (now() at time zone 'Asia/Seoul')::date
  and (t.is_completed = false or
    (t.completed_at at time zone 'Asia/Seoul')::date is distinct from e.completed_day);

-- plan_versions are append-only. Other diary records can be updated or deleted by their owner.
